name: Remanier le code
description: Créer une issue pour remanier le code
labels: [refactor]
body:
  - type: textarea
    id: description
    attributes:
      label: Description de l'issue
      description: |
        Quel est le problème que vous souhaitez résoudre ?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Quelle solution proposez-vous ?
      description: |
        Quelle solution ou amélioration proposez-vous pour résoudre le problème ?
    validations:
      required: true
  - type: textarea
    id: advantages
    attributes:
      label: Avantages et inconvénients
      description: |
        Quels sont les avantages et inconvenients de ce changement ?
    validations:
      required: false